<?php

/**
 * AssisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssisterRepository extends Doctrine\ORM\EntityRepository
{
    public function getRoomsOverbooked()
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder->select('ass')
            ->from('Assister', 'ass')
            ->join('ass.idSession', 'sess')
            ->join('sess.idSalle', 'sall')
            ->groupBy('ass.idSession')
            ->addGroupBy('sall.places')
            ->having('COUNT(ass.idEmploye) > sall.places');

            $query = $queryBuilder->getQuery();
            $results = $query->getSQL();
            $results = $query->getResult();

            return $results;


        $query = "SELECT ass.idSession
                  FROM \Assister ass
                  JOIN ass.idSession sess
                  JOIN sess.idSalle sall
                  GROUP BY sall.places, ass.idSession
                  HAVING COUNT(ass.idEmploye) > sall.places";

        return $this->_em->createQuery($query)->getResult();
    }
}