<?php

/**
 * AssisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssisterRepository extends Doctrine\ORM\EntityRepository
{
    public function getRoomsOverbooked()
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder->select('ass')
            ->from('Assister', 'ass')
            ->join('ass.idSession', 'sess')
            ->join('sess.idSalle', 'sall')
            ->where(':count > :places')
            ->setParameter('count', 'COUNT(ass.idEmploye)')
            ->setParameter('places', 'sall.places')
            ->groupBy('ass.idSession');

            $query = $queryBuilder->getQuery();
            $results = $query->getResult();

            return $results;


        // $query = "SELECT COUNT(ass.idEmploye) as cass, ass.idSession
        //           FROM \Assister ass
        //           JOIN ass.idSession sess
        //           JOIN sess.idSalle sall
        //           WHERE cass > sall.places
        //           GROUP BY ass.idSession";

        // return $this->_em->createQuery($query)->getResult();
    }
}