<?php

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends Doctrine\ORM\EntityRepository
{
    public function getMatieres($intitule)
    {
        $queryBuilder = $this->_em->createQueryBuilder();

        $queryBuilder->select('m')
            ->from('Matiere', 'm')
            ->where($queryBuilder->expr()->like('m.intitule', ':intitule'))
            ->setParameter('intitule', '%'.$intitule.'%');

            $query = $queryBuilder->getQuery();
            $results = $query->getResult();

            return $results;
    }
}