<?php

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends Doctrine\ORM\EntityRepository
{
    public function getRoomForSession($idMatiere)
    {
        return $this->_em->createQuery("select s from \Session s where s.idMatiere = ".$idMatiere)->getResult();
    }
}